### ISSUE TITLE
variable name formatter

### ISSUE THREAD

**Issue by markdanese** [renkun-ken/formattable#24]
Love this idea.  It might be nice to also have a function that will apply simple rules for the variable names to format them as well.  For example, include an option to make variable names title case, and replace "_" and "." with a space.  Probably could be set at the data.frame level.

**Comment by renkun-ken** [comment]
[This](http://stackoverflow.com/questions/15776732/how-to-convert-a-vector-of-strings-to-title-case) looks helpful. Let me think about it.

**Comment by markdanese** [comment]
The latest tools package has a toTitleCase() function.  It seems to have some intelligence to it, only capitalizing "important' words and ignoring others.
From CRAN news:  New function toTitleCase() in package tools, tailored to package titles.

> library(tools)
> toTitleCase("this is all lowercase")
[1] "this is all Lowercase"
> toTitleCase("test another entry")
[1] "Test Another Entry"

**Comment by renkun-ken** [comment]
Thanks for the information!

**Comment by renkun-ken** [comment]
For example, 

```r
library(formattable)
formattable(iris, col.names = gsub(".", " ", colnames(iris), fixed = TRUE))
```

This produces a formattable data frame with more friendly column names (spaces instead of dots). I think this is enough to serve your purpose because column naming can be more customized. `col.names` is actually passed to `knitr::kable` which by itself supports replacing the original column names of the supplied data frame.
