### ISSUE TITLE
Conditional formatting based on 2+ columns

### ISSUE THREAD

**Issue by cicevicek** [renkun-ken/formattable#34]
Hi,
I wonder whether it is possible to define a formatter based on multiple columns of a data.frame. I would like to do something along these lines...

p_format <- formatter("span",
  style = x ~ ifelse(x <= 0.05 && *my_second_variable* <= 0, "background-color:red",NA))

Thanks!
Jurgen.

**Comment by renkun-ken** [comment]
In commit 3abfa14fe8d1f3c9405f45a1d73001ebfbe3183b, a new feature is implemented for this request.

Previously, `formatter("span", ...)` accepts function and formula in `...` and they behave almost the same. Now `~expr` and `x ~ expr` will behave differently:

* `x ~ expr` will behave just like `function(x) expr` and only works for one column.
* `~expr` will be evaluated in the data frame so that you can directly use the multiple column names in `expr`.

For example, the following code makes up `mpg` in red for records satisfying `vs == 1` and `am == 1`:

```r
formattable(mtcars, list(mpg = formatter("span",
     style = ~ style(color = ifelse(vs == 1 & am == 1, "red", NA)))))
```

For more details, please read the documentation of `formatter` in the latest commit.
