### ISSUE TITLE
Easy way to reduce column width?

### ISSUE THREAD

**Issue by jschndr** [renkun-ken/formattable#38]
Hi, been loving formattable. Right now I am trying to reduce formattable column widths in a shiny app, the table I am working with is only 5 columns and it stretches across all available area! 

Thanks for your help and time :)

**Comment by timelyportfolio** [comment]
Do you have a code snippet of your Shiny app?  I think this should be relatively easy, but I want to make sure that I'm not missing anything.

**Comment by jds2711** [comment]
I am using the renderFormattable function for shiny... some simple code might look like:

 output$simple_totals <- renderFormattable({
    if(is.null(input$file1) & is.null(input$file2)) return()
    totals<-totals()
    
    as.htmlwidget(
      formattable(totals, list(Projection= color_text("black","darkgreen"),
                                 align=c('r','l'))))
  }) 
})

Thanks for your time!

**Comment by timelyportfolio** [comment]
Is `output$simple_totals` from `formattableOutput`?  I think you can just provide `width = "50%` as an argument.  Does this work?

**Comment by jds2711** [comment]
Yeap it is, and it worked! Thanks for your time, I was messing around with px stuff on the server side :s

**Comment by timelyportfolio** [comment]
@jds2711 great to hear.  Always love to see these get put to use.

**Comment by renkun-ken** [comment]
Feel free to reopen.

**Comment by eliobartos** [comment]
Hi, I have similar problem. When I look at my table fullscreen columns are to wide. If I put width = '50%' then it looks ok, but when I look at my dashboard half-screen then half of the screen is not used and table looks silly. But if I fixate it with pixels then it is not good also because when I look halfscreen part of the table is missing. 

Is there any way to have table not too big when full screen but use all the space when the screen is half screen?
